[theme]
base="light"
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#aaaaaa"
textColor = "#000000"
font = "sans serif"

[client]
showSidebarNavigation = false

[runner]
# Install a watcher to automatically rerun script if the file changes
magicEnabled = true